name: Check Commits and Send Email

on:
  schedule:
    - cron: '0 23 * * *'  
  workflow_dispatch:  

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:  # Passando os segredos como variáveis de ambiente
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python gitbot.py
